export const experience = [
  {
    company: "TVZ Corp",
    location: "Sao-Paulo, Brazil",
    category: "SaaS",
    role: "Lead Product Designer",
    period: "May 2025 - Present",
    highlights: [
      "Owned end-to-end product design for multiple SaaS initiatives, from discovery and research through high-fidelity execution and launch.",
      "Led design strategy for an AI-powered team collaboration platform, defining problem space, success metrics, and long-term product vision.",
      "Conducted primary user research and iterative validation to inform complex workflow decisions and reduce friction across core user journeys.",
      "Partnered closely with product managers and engineers to translate ambiguous requirements into scalable, production-ready solutions.",
      "Influenced roadmap prioritization by balancing user impact, technical feasibility, and business constraints.",
    ],
  },
  {
    company: "Moneta Technologies",
    location: "Abuja, Nigeria",
    category: "Fintech",
    role: "Senior Product Designer",
    period: "Nov 2022 - Mar 2025",
    highlights: [
      "Moneta Technologies was a CBN-regulated fintech spun out of Dreamlabs as a standalone legal entity; I transitioned with the product from its inception.",
      "Designed end-to-end user experiences for fintech SaaS products handling payments, financial data, and regulated workflows.",
      "Led UX strategy for complex transactional flows, ensuring clarity, trust, and compliance in high-risk user interactions.",
      "Collaborated with PMs and engineers to align design decisions with regulatory, security, and scalability constraints.",
      "Built and maintained shared design patterns and system components to improve consistency and velocity across teams.",
      "Conducted usability testing and iterative refinement on critical flows to reduce errors and improve task success rates.",
    ],
  },
  {
    company: "Dreamlabs",
    location: "Abuja, Nigeria",
    category: "SaaS",
    role: "Product Designer",
    period: "June 2022 - Mar 2025",
    highlights: [
      "Led discovery and design execution for multiple B2B SaaS products across fintech, healthcare, and enterprise domains.",
      "Defined product requirements, success metrics, and design direction in collaboration with clients and internal teams.",
      "Used data and qualitative feedback to iterate features post-launch and drive measurable adoption improvements.",
      "Led the design of Moneta, a fintech product that was subsequently incorporated as an independent CBN-licensed entity, Moneta Technologies, where I continued in a senior design role.",
    ],
  },
  {
    company: "ISCOM University",
    location: "Benin Republic",
    category: "EduTech",
    role: "UX Engineer",
    period: "Sep 2019 - Mar 2021",
    highlights: [
      "Supported launch and promotion of a digital learning platform, contributing to increased enrollment and remote admissions.",
      "Collaborated with non-technical stakeholders to translate product capabilities into clear benefits for students and administrators.",
    ],
  },
];
